## Практическое задание N 2

In [1]:
import numpy as np

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [6]:
A = np.array([[1,-2],[3,0]])
B = np.array([[4,-1], [0,5]])

In [7]:
(A, B)

(array([[ 1, -2],
        [ 3,  0]]),
 array([[ 4, -1],
        [ 0,  5]]))

In [8]:
A @ B

array([[  4, -11],
       [ 12,  -3]])

In [9]:
B @ A

array([[ 1, -8],
       [15,  0]])

In [10]:
A + B

array([[ 5, -3],
       [ 3,  5]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [11]:
A = np.array([[1,7], [3, -6]])
B = np.array([[0,5], [2,-1]])
C = np.array([[2,-4], [1, 1]])
(A, B, C)

(array([[ 1,  7],
        [ 3, -6]]),
 array([[ 0,  5],
        [ 2, -1]]),
 array([[ 2, -4],
        [ 1,  1]]))

In [13]:
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [15]:
A = np.array([[4,1],[5,-2],[2,3]])
(A, A.T)

(array([[ 4,  1],
        [ 5, -2],
        [ 2,  3]]),
 array([[ 4,  5,  2],
        [ 1, -2,  3]]))

In [16]:
A @ A.T

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [17]:
A.T @ A

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [20]:
def matrix_multi(A, B):
    A_m = len(A)
    A_n = len(A[0])
    B_n = len(B)
    B_k = len(B[0])
    if A_n != B_n:
        raise Exception("Размеры матриц не согласованы")
    C = [[[] for i in range(A_m)] for i in range(B_k)]

    for i in range(A_m):
        for j in range(B_k):
            sum0 = 0
            for p in range(A_n):
                sum0 += A[i][p] * B[p][j]
            C[i][j] = sum0
    return C

In [21]:
A1 = [[1, 2, 3], [2, 3, 4]]
B1 = [[2, 1], [3, 1], [1, 1]]
(A1, B1)

([[1, 2, 3], [2, 3, 4]], [[2, 1], [3, 1], [1, 1]])

In [22]:
matrix_multi(A1,B1)

[[11, 6], [17, 9]]

In [23]:
matrix_multi(B1,A1)

[[4, 7, 10], [5, 9, 13], [3, 5, 7]]

In [24]:
A = np.array([[1, 2, 3], [2, 3, 4]])
B = np.array([[2, 1], [3, 1], [1, 1]])
(A, B)

(array([[1, 2, 3],
        [2, 3, 4]]),
 array([[2, 1],
        [3, 1],
        [1, 1]]))

In [25]:
A @ B

array([[11,  6],
       [17,  9]])

In [26]:
B @ A

array([[ 4,  7, 10],
       [ 5,  9, 13],
       [ 3,  5,  7]])