## Практическое задание N 4.1

In [1]:
import numpy as np

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

> в тетради

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

In [7]:
A=np.array([[3,-1,1],[2,-5,-3],[1,1,-1]]) 
A_r=np.append(A,[[4],[-17],[0]], axis=1)
(A, A_r)

(array([[ 3, -1,  1],
        [ 2, -5, -3],
        [ 1,  1, -1]]),
 array([[  3,  -1,   1,   4],
        [  2,  -5,  -3, -17],
        [  1,   1,  -1,   0]]))

In [9]:
np.linalg.matrix_rank(A), np.linalg.matrix_rank(A_r), A.shape

(3, 3, (3, 3))

> система совместна и имеет 1 решение 

    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

In [13]:
A=np.array([[2,-4,6], [1, -2, 3], [3, -6, 9]]) 
A_r=np.append(A,[[1],[-2],[5]], axis=1)
(A, A_r)

(array([[ 2, -4,  6],
        [ 1, -2,  3],
        [ 3, -6,  9]]),
 array([[ 2, -4,  6,  1],
        [ 1, -2,  3, -2],
        [ 3, -6,  9,  5]]))

In [14]:
np.linalg.matrix_rank(A), np.linalg.matrix_rank(A_r), A.shape

(1, 2, (3, 3))

>система не совместна - нет решений

    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [15]:
A=np.array([[1, 2, 5], [3, 1, -8]]) 
A_r=np.append(A,[[4],[-2]], axis=1)
(A, A_r)

(array([[ 1,  2,  5],
        [ 3,  1, -8]]),
 array([[ 1,  2,  5,  4],
        [ 3,  1, -8, -2]]))

In [16]:
np.linalg.matrix_rank(A), np.linalg.matrix_rank(A_r), A.shape

(2, 2, (2, 3))

> система недоопределенная, имеет oo - решений

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

>в тетради

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

>в тетради

## Практическое задание N 4.2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

>в тетради. Здесь проверка

In [39]:
A_orig=np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b=[10,-2,1]
A_orig, b

(array([[10, 10,  5],
        [-2, -2, -3],
        [ 1,  1,  1]]),
 [10, -2, 1])

In [40]:
np.linalg.det(A_orig)

42.99999999999998

In [45]:
A=A_orig.copy()
A.T[0]=b
A, np.linalg.det(A)

(array([[10, -1,  5],
        [-2,  1, -3],
        [ 1,  4,  1]]),
 86.00000000000004)

In [46]:
A=A_orig.copy()
A.T[1]=b
A, np.linalg.det(A)

(array([[ 2, 10,  5],
        [ 1, -2, -3],
        [ 2,  1,  1]]),
 -43.000000000000014)

In [47]:
A=A_orig.copy()
A.T[2]=b
A, np.linalg.det(A)

(array([[ 2, -1, 10],
        [ 1,  1, -2],
        [ 2,  4,  1]]),
 42.99999999999998)

In [48]:
A.shape

(3, 3)

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    
__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [52]:
import numpy.linalg as la
def matrix_kramer(A, b):
    if A.shape[0] != A.shape[1]:
        raise Exception('Размерность не совпадает')
    det = la.det(A)
    R = []
    for i in range(A.shape[0]):
        A_s = A.copy()
        A_s.T[i] = b
        R.append(la.det(A_s) / det)
    return R

In [53]:
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = [10, -2, 1]
print(matrix_kramer(A, b))

[2.0000000000000018, -1.0000000000000009, 1.0]


In [55]:
A = np.array([[1,-2], [3, -4]])
b = [1, 7]
print(matrix_kramer(A, b))

[4.999999999999998, 1.9999999999999991]
