## Практическое задание N 4

In [1]:
import numpy as np

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

> в тетради

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

In [7]:
A=np.array([[3,-1,1],[2,-5,-3],[1,1,-1]]) 
A_r=np.append(A,[[4],[-17],[0]], axis=1)
(A, A_r)

(array([[ 3, -1,  1],
        [ 2, -5, -3],
        [ 1,  1, -1]]),
 array([[  3,  -1,   1,   4],
        [  2,  -5,  -3, -17],
        [  1,   1,  -1,   0]]))

In [9]:
np.linalg.matrix_rank(A), np.linalg.matrix_rank(A_r), A.shape

(3, 3, (3, 3))

> система совместна и имеет 1 решение 

    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

In [13]:
A=np.array([[2,-4,6], [1, -2, 3], [3, -6, 9]]) 
A_r=np.append(A,[[1],[-2],[5]], axis=1)
(A, A_r)

(array([[ 2, -4,  6],
        [ 1, -2,  3],
        [ 3, -6,  9]]),
 array([[ 2, -4,  6,  1],
        [ 1, -2,  3, -2],
        [ 3, -6,  9,  5]]))

In [14]:
np.linalg.matrix_rank(A), np.linalg.matrix_rank(A_r), A.shape

(1, 2, (3, 3))

>система не совместна - нет решений

    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [15]:
A=np.array([[1, 2, 5], [3, 1, -8]]) 
A_r=np.append(A,[[4],[-2]], axis=1)
(A, A_r)

(array([[ 1,  2,  5],
        [ 3,  1, -8]]),
 array([[ 1,  2,  5,  4],
        [ 3,  1, -8, -2]]))

In [16]:
np.linalg.matrix_rank(A), np.linalg.matrix_rank(A_r), A.shape

(2, 2, (2, 3))

> система недоопределенная, имеет oo - решений

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.